# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np

In [5]:
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
import numpy as np

In [12]:
array1 = np.arange(10)
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:

array3 = np.ones(10, dtype = int)
array4 = array3.reshape(2,5)
print(array4)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
print(array2,array4)
np.vstack((array2,array4))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [23]:
import numpy as np

In [24]:
array1 = np.arange(0,10)
array2 = array1.reshape(2,5)
array3 = np.ones(10 , dtype = int)
array4 = array3.reshape(2,5)
print(array2,array4)
np.hstack((array2,array4))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [25]:
import numpy as np

In [26]:
array2 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(array2)
array2.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [3]:
import numpy as np

In [5]:
array1 = np.asarray([[0,1,2,3,4],[5,6,7,8,9]])
array1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [30]:
import numpy as np

In [31]:
array1 = np.arange(15)
array2 = array1.reshape(-1,3)
print(array2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [32]:
import numpy as np

In [33]:
array1 = np.arange(25)
array2 = array1.reshape(5,5)
print(array2)
np.square(array2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
import numpy as np

In [34]:
np.random.seed(789)
array1=np.random.randint(30, size= (5,6))
print(array1)
array1.mean()

[[19 14 18  1 12 26]
 [ 3 20 24 27 20 17]
 [ 8 16  1  1 25 24]
 [25 15  4  1  4 17]
 [ 3 24  1 20 25  6]]


14.033333333333333

## Question:9

### Find the standard deviation of the previous array in Q8?

In [35]:
import numpy as np

In [36]:
np.random.seed(789)
array1=np.random.randint(30, size= (5,6))
print(array1)


[[19 14 18  1 12 26]
 [ 3 20 24 27 20 17]
 [ 8 16  1  1 25 24]
 [25 15  4  1  4 17]
 [ 3 24  1 20 25  6]]


In [37]:
np.std(array1)

9.199577284974685

## Question:10

### Find the median of the previous array in Q8?

In [38]:
import numpy as np

In [39]:
np.random.seed(789)
array1=np.random.randint(30, size= (5,6))
print(array1)

[[19 14 18  1 12 26]
 [ 3 20 24 27 20 17]
 [ 8 16  1  1 25 24]
 [25 15  4  1  4 17]
 [ 3 24  1 20 25  6]]


In [40]:
np.median(array1)

16.5

## Question:11

### Find the transpose of the previous array in Q8?

In [41]:
import numpy as np

In [42]:
np.random.seed(789)
array1=np.random.randint(30, size= (5,6))
print(array1)

[[19 14 18  1 12 26]
 [ 3 20 24 27 20 17]
 [ 8 16  1  1 25 24]
 [25 15  4  1  4 17]
 [ 3 24  1 20 25  6]]


In [44]:
array1.T

array([[19,  3,  8, 25,  3],
       [14, 20, 16, 15, 24],
       [18, 24,  1,  4,  1],
       [ 1, 27,  1,  1, 20],
       [12, 20, 25,  4, 25],
       [26, 17, 24, 17,  6]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [46]:
import numpy as np

In [49]:
array1 = np.arange(16)
array2 = array1.reshape(4,4)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [51]:
np.diagonal(array2)

array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [53]:
import numpy as np

In [55]:
array1 = np.arange(16)
array2 = array1.reshape(4,4)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [54]:
np.linalg.det(array2)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [56]:
import numpy as np

In [61]:
array= np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
print(np.percentile(array,5)  )
print(np.percentile(array,95) )

0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [63]:
import numpy as np

In [64]:
array = np.arange(100)
array1 = array.reshape(10,10)
print(array1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [11]:
array_null_value = np.asarray([[1,2,3,4,None],[5,6,7,8,None]])

null_value = lambda array1: print("Array has null values")if None in array1 else print("Array does not have any null value")

null_value(array1)

Array does not have any null value
